### ISSUE TITLE
UILabel styler documentation missing

### ISSUE THREAD

**Issue by fvonhoven** [infinitered/rmq#171]
The UILabel styler supports `adjusts_font_size` but I couldn't find it in the documentation.
http://rubymotionquery.com/?s=adjusts_font_size&post_type=document

**Comment by squidpunch** [comment]
Yeah there's a bunch of stylers that aren't actually documented - on the flipside to document every single styler available might be tricky to format in a manageable way...

I requested that perhaps we have all the stylers listed (and the iOS counterparts) making it at least easy to search what is available if you know the iOS version - etc..

**Comment by twerth** [comment]
I documented all the stylers in RedPotion, FYI.
