### ISSUE TITLE
How can I pass a table cell's title to a label in an overlay?

### ISSUE THREAD

**Issue by elzggr** [infinitered/rmq#175]
Hi! 

I have table cells which are populated with arguments I pull from a json object such as the title and subtitle of each cells.

When I tap on a cell, this brings up an overlay containing a label. 
How can I can I pass the tapped cell's title unto this very  label?

Thanks in advance

**Comment by GantMan** [comment]
Got this in a repo?   I think I see what you're saying, but it would be really easy if you had some code for me to mess with :)

**Comment by elzggr** [comment]
Hi @GantMan,

I've extracted the relevant code here https://gist.github.com/elzggr/f438a03fc830b8a6d270#file-event_app_code_extract-rb

Thanks for the help!

**Comment by squidpunch** [comment]
I'll post a few options on the gist that come to mind, lets see if @GantMan has a better suggestion too :+1:

**Comment by elzggr** [comment]
@squidpunch much appreciated! :)

**Comment by squidpunch** [comment]
glad to help :)

**Comment by twerth** [comment]
Closing this as it seems to be solved
