### ISSUE TITLE
How to use RMQ to style a Promotion table cell?

### ISSUE THREAD

**Issue by elzggr** [infinitered/rmq#191]
Hi guys!

Just started using RMQ a week ago (changed my life :+1: :+1: :+1:  !!!) and I was wondering if you guys had a gist or some type of example of how to style a promotion table cell with RMQ such as adding a rounded image , different text labels etc....

Much appreciated!

**Comment by twerth** [comment]
Hey elzggr, I don't have a gist, but this is what we're using: https://github.com/infinitered/redpotion

We haven't officially released RedPotion yet, but we will soon. The app in that repo has both a normal SDK table and a Promotion table example (plus there is a generator). We are using RedPotion for all of our projects right now.

**Comment by elzggr** [comment]
@twerth thanks!
