### ISSUE TITLE
No Device Specific Testing

### ISSUE THREAD

**Issue by GantMan** [infinitered/rmq#208]
Tests need to be run for multiple devices.   Things may pass for default (iPhone 6) but fail on iPhone 4s or 5.   We need a good way to have travis run everything.

**Comment by squidpunch** [comment]
@GantMan is this related to the color thing?  Right now all tests pass on any simulator I try - which means travis wouldnt catch anything.

I could easily expand out travis to include other device types and framework levels, etc - but I think the failures you are talking about actually only happen on a real device like #194 / #209 ?

**Comment by GantMan** [comment]
no, the tests failed for iPhone 5.   It's completely catchable.

**Comment by squidpunch** [comment]
Hrmm, Locally all tests passed for me on the 5 which is why I asked

Maybe we can chat on slack about this later...ish

**Comment by squidpunch** [comment]
@GantMan does my travis PR that pulls in the 5 (and covering the 32 bit arch) cover this?  Or should we go further?

**Comment by GantMan** [comment]
I think that's good for now.   AS Apple grows and possibly supports new archs, we'll need to add devices as needed, but we have a template now :)

**Comment by squidpunch** [comment]
Sounds good :)
