### ISSUE TITLE
Inconsistency with adjustsFontSizeToFitWidth

### ISSUE THREAD

**Issue by GantMan** [infinitered/rmq#217]
The styler for adjustsFontSizeToFitWidth is different from UILabel to UITextField

UILabel -> `adjusts_font_size`
UITextField ->  `adjusts_font_size_to_fit_width`

aliases are needed to make this consistent.

Also, only one of these is tested, it seems - Notice here:
https://github.com/infinitered/rmq/search?utf8=%E2%9C%93&q=adjustsFontSizeToFitWidth

**Comment by markrickert** [comment]
the actual method names for UILabel and UITextfield are mirrors of the RM stylers. I say we leave alone (notwithstanding the tests) since it behaves just like you'd expect based on the API documentation of those two components.

**Comment by GantMan** [comment]
@markrickert I think you're mistaken.   Or maybe I don't understand what you're saying.

https://github.com/infinitered/rmq/blob/a7465db43196df3d5377cf43087024708d21b156/motion/ruby_motion_query/stylers/ui_label_styler.rb#L58-L59

As you can see here, the API documentation of the component is `adjustsFontSizeToFitWidth` but the styler is simply `adjusts_font_size`.   Where as on the UITextField also is calling `adjustsFontSizeToFitWidth` but the styler is the FULL name `adjusts_font_size_to_fit_width`.

https://github.com/infinitered/rmq/blob/d6b992aac9928d7577b18904451e8e60790fb82b/motion/ruby_motion_query/stylers/ui_text_field_styler.rb#L37

That is what I'm saying is inconsistent.

**Comment by markrickert** [comment]
Aha. gotcha. Fix away!

**Comment by GantMan** [comment]
I'll probably get to this today or tomorrow, depending :)   Issues make sure I don't forget.
