### ISSUE TITLE
Document how to access tag values

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/rmq#228]
http://rubymotionquery.com/?s=tag&post_type=document

``` ruby
# You can optionally store a value in the tag, which can be super useful in some rare situations
rmq(my_view).tag(your_tag: 22)
rmq(my_view).tag(your_tag: 22, your_other_tag: 'Hello world')
```

Doesn't mention how to access the `22` and `Hello World` values. Don't have time to figure it out atm but figured I'd post an issue so I don't forget.

**Comment by squidpunch** [comment]
@jamonholmgren I just poked around to figure it out for you - I can document it later, though I'd like to check with @twerth that this is the right API and I'm not just digging into internals here.....

```
(main)> rmq(my_view).tag(your_tag: 22)
=> RMQ 4586369712. 1 selected. selectors: [#<UIButton:0x11151d4d0>]. .log for more info
[#<UIButton:0x11151d4d0>]
(main)> my_view.rmq_data.tags[:your_tag]
=> 22
```

**Comment by jamonholmgren** [comment]
:+1:

**Comment by twerth** [comment]
Yeah, that's the original way, although I thought we added a nicer way to do it. I'll poke around.

**Comment by twerth** [comment]
I don't see anything else, be nice to have something nicer, let say:

```ruby
rmq(my_view).tag_data(:your_tag)
```

Or some such.

**Comment by jamonholmgren** [comment]
What about:

```ruby
rmq(my_view).tags(:your_tag) # => value here
```

**Comment by squidpunch** [comment]
I havent actually used tags to store data inside, but I'd almost prefer @jamonholmgren's suggestion so its not one other attribute to remember.  If I am pushing data in with `.tag`, I want to pull it out with `.tag` IMHO.

**Comment by squidpunch** [comment]
@jamonholmgren @twerth I started throwing something together for this, what do you guys think about tag collisions?  Should we require this to only be on a single selected view? Warn users?  etc. 

Example
```ruby
rmq.append(UIView, :one).tag(important: 10)
rmq.append(UIView, :two).tag(important: 12)

rmq.all.tags(:important)
#or
rmq(UIView).tags(:important)
```

what do we expect here?  Should we only allow selections of tags when we have one view wrapped, take the latest value?  return an array of values or something to that effect?  

My gut feels that the way we would use a tag, would be its something set on one view item, and then we should be pulling it from one view item - rather than a blanket selection, but I'd like others input before I continue on with implementation :)

**Comment by squidpunch** [comment]
in other words

`rmq.all.tags(:important)` should either warn or return an array of the values possibly...

but the expected behavior (maybe forced by us?) would be `rmq(:one).tags(:important)`

**Comment by jamonholmgren** [comment]
I think returning an array of the values makes the most sense to me.

**Comment by squidpunch** [comment]
I just don't know if there is a use case for that. Imagine 10 views with the same tag and requesting row.all.tags what would you do with with that array?

There is no harm in giving them all in an array and it matches what we do with multiple views in a selection. So maybe that makes sense.

**Comment by jamonholmgren** [comment]
Yeah, I don't think I'd ever use that feature, so it doesn't matter too much to me (same with multiple views and `.get`). Just seems consistent.
