### ISSUE TITLE
Live Reloading, how to handle TableViewCell's stylesheet?

### ISSUE THREAD

**Issue by zhigang1992** [infinitered/rmq#241]
We are using `include` in stylesheet like this:
```ruby
class TableControllerStylesheet < ApplicationStylesheet

  include TableCellStylesheet

  def setup
    # Add stylesheet specific setup stuff here.
    # Add application specific setup stuff in application_stylesheet.rb
  end

  def table(st)
    st.background_color = color.gray
  end
end
```
So when the `TableCellStylesheet` is updated, style is not applied.
Any thought on this?

**Comment by twerth** [comment]
Yeah, this is a problem and so is ApplicationStylesheet. We'll fix them in the same way.

**Comment by twerth** [comment]
Hopefully I can get to it this weekend. Thank you Zhigang, and please point out any other problems you have.

**Comment by zhigang1992** [comment]
@twerth hey there, did not expect to see a response so quickly,... I just sent out a pull request. can you check it out? :)
Might not be proper way of doing it, but it works.

**Comment by twerth** [comment]
Thanks. I'll review it later. I think we need to worry about order too.
