### ISSUE TITLE
Accessing rmq.color.custom_color crashes in AppDelegate on_load

### ISSUE THREAD

**Issue by zhigang1992** [infinitered/rmq#252]
Error:
```
custom_color not defined in rmq.'s color class.
```

**Comment by squidpunch** [comment]
sounds like application_setup wasn't run on your stylesheet yet.  Are you initializing a controller to display before calling this color method?  Where is the stylesheet set in that controller?

**Comment by zhigang1992** [comment]
```ruby
class AppDelegate < PM::Delegate
  include CDQ

  status_bar true, animation: :fade

  def on_load(app, options)
    cdq.setup
    open LoginScreen.new(nav_bar: true)
    puts rmq.color.theme_500
  end
end
```
Not sure where it's initialized, it's pretty a plain project that I just started.

**Comment by zhigang1992** [comment]
@squidpunch it's crashing on `puts rmq.color.theme_500`

**Comment by squidpunch** [comment]
so `theme_500` is defined in application stylesheet?  I would expect this to be fine because the LoginScreen initialization should call the stylesheet and then call setup.

I will throw together a quick app and see if I can recreate the bug and try and work through it :+1:

**Comment by twerth** [comment]
Yeah, this an architecture failure on my part. You have to open a controller before ApplicationStylesheet#setup is run. However as David notes, it should be there after the LoginScreen is loaded.

A work around if you need colors before any screen is loaded you can do:

```
ApplicationStylesheet.new.application_setup
```

**Comment by twerth** [comment]
We're not getting a response, so closing.
