### ISSUE TITLE
ProMotion table cells disappear when using rmq_live_stylesheets

### ISSUE THREAD

**Issue by twerth** [infinitered/rmq#254]
I'm experiencing this in RedPotion, but I'm sure it's happening with just RMQ and PM also.

Just modify a custom cell used by a PM table.

@jamonholmgren

**Comment by jamonholmgren** [comment]
Odd. Are they still in the view hierarchy?

**Comment by twerth** [comment]
Yes. Let me create most basic app, I'll send it to ya

**Comment by skellock** [comment]
Fixed with #261
