### ISSUE TITLE
on(:long_press) fires on both up and down actions

### ISSUE THREAD

**Issue by markrickert** [infinitered/rmq#268]
```ruby
rmq(:some_view).on(:long_press) do 
  mp "long pressed!"
end
```

will show:

```
long pressed!
long pressed!
```
in the REPL because the action is triggered on both the gesture recognizer realizing it has been a long press and again on the user letting go of the long press.

Here's how i've handled it in [ProMotion](https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/table/extensions/longpressable.rb#L16-L17): 

```ruby
def on_long_press(gesture)
  return unless gesture.state == UIGestureRecognizerStateBegan
  #other logic
end
```

Is this expected behavior or a bug? I know it's impossible to test long press gestures in the simulator right now.

**Comment by GantMan** [comment]
That's definitely a bug.
