### ISSUE TITLE
Add accessibility to RMQ Animations

### ISSUE THREAD

**Issue by markrickert** [infinitered/rmq#277]
Use `UIAccessibilityIsVoiceOverRunning()` to detect if voiceover is on and if so, don't actually animate the object(s), just change the state(s) and run the callbacks.

From @amirrajan's RubyMotion #Inspect2015 talk - if you animate controls, they're not available for swiping in voiceover mode for the blind.

cc/ @austinseraphin - we missed you this year at Inspect!

**Comment by austinseraphin** [comment]
Beautiful!
