### ISSUE TITLE
[RMQ ERROR] on v10.11.1

### ISSUE THREAD

**Issue by jney** [infinitered/rmq#306]
since last ios update (yesterday), my team and i got such errors while running our specs :

```
[RMQ ERROR]  style_name :list_view_cell doesn't exist for a ProductListView::ItemWithProductCell. Add 'def list_view_cell(st)' to SignOnControllerStylesheet class
```

dis someone herer notice same behaviour ?

**Comment by jamonholmgren** [comment]
Standard question, sorry: I assume you did `rake clean:all` and reset your simulator?

I haven't noticed this behavior yet, but I haven't built an app yet since updating. Maybe @kevinvangelder ?

**Comment by squidpunch** [comment]
this is an Error/warning that has been in RMQ for a while [from here](https://github.com/infinitered/rmq/blob/7e3d17bdc9ee7a54add05c76dea9feaa3e11b563/motion/ruby_motion_query/stylesheet.rb#L200-L206)  

Short answer, you must be trying to apply a style `:list_view_cell` on a view that is of class type `ProductListView::ItemWithProductCell` and the test you are running is testing on a controller that is setting the stylesheet to `SignOnControllerStylesheet` (most likely `SignOnController`)

**Comment by squidpunch** [comment]
@jney did that answer your question, is there still an issue here?

**Comment by jney** [comment]
no issue there, thank you guys

**Comment by squidpunch** [comment]
glad to help! :+1:
