### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by wndxlori** [infinitered/rmq#333]
Not sure who's responsible for that, but...
<img width="595" alt="Screen Shot 2020-09-11 at 4 04 21 PM" src="https://user-images.githubusercontent.com/17056/92976763-88502d80-f448-11ea-8c94-fead00489abc.png">

**Comment by wndxlori** [comment]
@twerth or @jamonholmgren?

**Comment by twerth** [comment]
Fixed
